/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCriarRouteImport } from './routes/_authenticated/criar'
import { Route as AuthenticatedMemoriaRouteImport } from './routes/_authenticated/memoria'
import { Route as AuthenticatedHistoricoIndexRouteImport } from './routes/_authenticated/historico.index'
import { Route as AuthenticatedHistoricoIdRouteImport } from './routes/_authenticated/historico.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCriarRoute = AuthenticatedCriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemoriaRoute = AuthenticatedMemoriaRouteImport.update({
  id: '/memoria',
  path: '/memoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoIndexRoute =
  AuthenticatedHistoricoIndexRouteImport.update({
    id: '/historico/',
    path: '/historico/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoIdRoute =
  AuthenticatedHistoricoIdRouteImport.update({
    id: '/historico/$id',
    path: '/historico/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/criar': typeof AuthenticatedCriarRoute
  '/memoria': typeof AuthenticatedMemoriaRoute
  '/historico/$id': typeof AuthenticatedHistoricoIdRoute
  '/historico/': typeof AuthenticatedHistoricoIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/criar': typeof AuthenticatedCriarRoute
  '/memoria': typeof AuthenticatedMemoriaRoute
  '/': typeof AuthenticatedIndexRoute
  '/historico/$id': typeof AuthenticatedHistoricoIdRoute
  '/historico': typeof AuthenticatedHistoricoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/criar': typeof AuthenticatedCriarRoute
  '/_authenticated/memoria': typeof AuthenticatedMemoriaRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/historico/$id': typeof AuthenticatedHistoricoIdRoute
  '/_authenticated/historico/': typeof AuthenticatedHistoricoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/criar' | '/memoria' | '/historico/$id' | '/historico/'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/criar' | '/memoria' | '/' | '/historico/$id' | '/historico'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/criar'
    | '/_authenticated/memoria'
    | '/_authenticated/'
    | '/_authenticated/historico/$id'
    | '/_authenticated/historico/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/criar': {
      id: '/_authenticated/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof AuthenticatedCriarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memoria': {
      id: '/_authenticated/memoria'
      path: '/memoria'
      fullPath: '/memoria'
      preLoaderRoute: typeof AuthenticatedMemoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico/': {
      id: '/_authenticated/historico/'
      path: '/historico'
      fullPath: '/historico/'
      preLoaderRoute: typeof AuthenticatedHistoricoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico/$id': {
      id: '/_authenticated/historico/$id'
      path: '/historico/$id'
      fullPath: '/historico/$id'
      preLoaderRoute: typeof AuthenticatedHistoricoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCriarRoute: typeof AuthenticatedCriarRoute
  AuthenticatedMemoriaRoute: typeof AuthenticatedMemoriaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedHistoricoIdRoute: typeof AuthenticatedHistoricoIdRoute
  AuthenticatedHistoricoIndexRoute: typeof AuthenticatedHistoricoIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCriarRoute: AuthenticatedCriarRoute,
  AuthenticatedMemoriaRoute: AuthenticatedMemoriaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedHistoricoIdRoute: AuthenticatedHistoricoIdRoute,
  AuthenticatedHistoricoIndexRoute: AuthenticatedHistoricoIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
